services:
#    ecortex_product_manager.example:
#        class: Ecortex\ProductManagerBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
parameters:
    ecortex_product_manager.beginLineTest:  0
    ecortex_product_manager.nbLinesTest:    120

