<?php

namespace Ecortex\ProductManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getByRefAndProvider($ref, $provider_id) {
        $q = $this->createQueryBuilder('p')
            ->where('p.ref = :ref')
            ->setParameter('ref', $ref)
            ->join('p.provider', 'pro')
            ->addSelect('pro')
            ->andWhere('pro.id = :pro_id')
            ->setParameter('pro_id', $provider_id)
            ->leftJoin('p.rangePrices', 'r')
            ->addSelect('r')
            ->leftJoin('r.productOptions', 'o')
            ->addSelect('o')
            ->getQuery();

        $result = $q->getSingleResult();

        return $result;
    }
}
