<?php

namespace Ecortex\ProductManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RangePriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RangePriceRepository extends EntityRepository
{
}
